alias rebash='source ~/.bashrc'
alias ea='emacs ~/.bash_aliases'
alias erc='emacs ~/.bashrc'
alias gits='git status'
alias gitb='git branch'
alias realrobot='unset ROBOT; unset ROS_HOSTNAME; export ROS_MASTER_URI=http://c1:11311; export ROS_IP=$MY_IP'
alias int='cd ~/rosbuild_ws/pr2_pbd/pr2_pbd_interaction/src'